name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: oracle-actions/setup-java@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          -Porg.gradle.java.installations.auto-download=false
          -Dplatform.tooling.support.tests.enabled=true
          "-Dscan.value.GitHub job=${{ github.job }}"
          javaToolchains
          ${{ inputs.arguments }}
