build: off

install:
  - cinst jdk9 -version 9.0.1.11 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk9
  - SET PATH=C:\jdk9\bin;%PATH%

test_script:
  - gradlew -version
  - gradlew build --stacktrace
