stages:  
- build  
- test  
- report

compile:   
  stage: build
  script:    
    - ./gradlew compileJava
  tags:   
    - run_concurrently_node10
    
sigridci:
  stage: report
  script:
    - git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci
    - ./sigridci/sigridci/sigridci.py --customer opensource --system junit --source . --targetquality 4.0
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
