# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: src/azure/azure-gradle-step.yml

- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  steps:
    - template: src/azure/azure-gradle-step.yml

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
    - template: src/azure/azure-gradle-step.yml
