stages:
  - stage: Report
    jobs:
    - job: SigridCI
      pool:
        vmImage: "windows-latest"
      container: python:3-windowsservercore-1809
      continueOnError: true
      steps:
      - script: "python --version"
      - script: "pip install --upgrade certifi"
      - script: "python -c \"import urllib.request; print(urllib.request.urlopen('https://sigrid-says.com').status)\""
      - script: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
      - script: "python sigridci\\sigridci\\sigridci.py --customer opensource --system junit --source . --targetquality 3.5"
        env:
          SIGRID_CI_ACCOUNT: $(SIGRID_CI_ACCOUNT)
          SIGRID_CI_TOKEN: $(SIGRID_CI_TOKEN)
        continueOnError: true
      - publish: sigrid-ci-output
        artifact: sigrid-ci-output
