[versions]
apiguardian = "1.1.1"
assertj = "3.19.0"
junit4 = "4.13.2"
junit4Osgi = "4.13.2_1"
junit4Min = "4.12"
log4j = "2.14.1"
opentest4j = "1.2.0"

[libraries]
apiguardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version = "0.17.0" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bartholdy = { module = "de.sormuras:bartholdy", version = "0.2.3" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.104" }
commons-io = { module = "commons-io:commons-io", version = "2.8.0" }
groovy3 = { module = "org.codehaus.groovy:groovy", version = "3.0.7" }
groovy2-bom = { module = "org.codehaus.groovy:groovy-bom", version = "2.5.14" }
junit4 = { module = "junit:junit", version = { strictly = "[4.12,)", prefer = "4.13.2" } }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.4.3" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
mockito = { module = "org.mockito:mockito-junit-jupiter", version = "3.9.0" }
opentest4j = { module = "org.opentest4j:opentest4j", version.ref = "opentest4j" }
picocli = { module = "info.picocli:picocli", version = "4.6.1" }
slf4j-julBinding = { module = "org.slf4j:slf4j-jdk14", version = "1.7.30" }
spock1 = { module = "org.spockframework:spock-core", version = "1.3-groovy-2.5" }
univocity-parsers = { module = "com.univocity:univocity-parsers", version = "2.9.1" }

[bundles]
log4j = ["log4j-core", "log4j-jul"]
