name: Set up Gradle JDK
description: Sets up the JDK required to run Gradle
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
