name: Check out, set up JDKs, and run Gradle
description: Sets up a JDK and env var
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-test-jdk
    - uses: ./.github/actions/setup-gradle-jdk
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          -Porg.gradle.java.installations.auto-download=false
          -Dplatform.tooling.support.tests.enabled=true
          javaToolchains
          ${{ inputs.arguments }}
    - uses: actions/upload-artifact@v2
      with:
        name: Test Distribution trace files (${{ github.job }})
        path: '**/build/test-results/*/trace.json'
