name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
inputs:
  distribution:
    required: true
    description: 'The JDK distribution to use'
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 8
        check-latest: true
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
