name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
runs:
  using: "composite"
  steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Prepare JDK8 env var
      shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
