name: Gradle Dependency Submission

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  dependency-submission:
    if: github.repository == 'junit-team/junit5'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 1
    - name: Setup Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      with:
        distribution: temurin
        java-version: 21
        check-latest: true
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@473878a77f1b98e2b5ac4af93489d1656a80a5ed # v4
