name: JUnit 5 CI

on:
  push:
    branches:
    - master
    - 'releases/*'
    - 'marc/gh-actions'
  pull_request: 
    branches:
    - master
    - 'releases/*'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: junitteam/build:latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10
    - name: OpenJDK 12
      run: |
        ./gradlew --version
#        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true build
    - name: OpenJDK 13
      run: |
        ./gradlew --version
        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true -PjavaHome=$JDK13 build
    - name: OpenJDK 14
      run: |
        ./gradlew --version
        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true -PjavaHome=$JDK14 build

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10
    - run: choco install openjdk --version 12.0.2
      shell: bash
    - name: Test
      run: |
        export JAVA_HOME="C:\Program Files\OpenJDK\jdk-12.0.2"
        export PATH="$JAVA_HOME/bin:$PATH"
        ./gradlew --version
        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true build
      shell: bash
      env:
       LC_ALL: en_US.UTF-8

  mac:
    name: Mac OS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10
    - name: Test
      run: |
        export JAVA_HOME="${JAVA_HOME_12_X64}"
        export PATH="$JAVA_HOME/bin:$PATH"
        ./gradlew --version
        ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true build
      shell: bash
      env:
       LC_ALL: en_US.UTF-8
