name: Reproducible build

on:
  push:
    branches:
    - main
    - 'releases/*'
  pull_request:
    branches:
    - '*'

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Prepare JDK17 env var
      shell: bash
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: Build and compare checksums
      shell: bash
      run: |
        ./gradlew javaToolchains -Porg.gradle.java.installations.auto-download=false
        ./src/checkBuildReproducibility.sh
