name: Reproducible build

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '*'

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Restore Gradle cache and display toolchains
      uses: ./.github/actions/run-gradle
      with:
        arguments: --quiet
    - name: Build and compare checksums
      env:
        JAVA_HOME: ${{env.JAVA_HOME_17_X64}}
      shell: bash
      run: |
        ./gradle/scripts/checkBuildReproducibility.sh
