name: Reproducible build

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '*'

permissions: read-all

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 1
    - name: Restore Gradle cache and display toolchains
      uses: ./.github/actions/run-gradle
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        arguments: |
          --quiet \
          --configuration-cache
    - name: Build and compare checksums
      shell: bash
      run: |
        ./gradle/scripts/checkBuildReproducibility.sh
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      if: ${{ always() }}
      with:
        name: Open Test Reports (${{ github.job }})
        path: '**/build/reports/open-test-report.html'
